name: MERN App Deployment

on:
  workflow_dispatch:  # Manual trigger
  push:
    branches:
      - main  # Trigger when pushing to main in CI/CD repo

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout CI/CD Repo
        uses: actions/checkout@v3

      - name: Checkout MERN App Repo
        uses: actions/checkout@v3
        with:
          repository: Abinaya-251/mernapp  # Repo with MERN code
          ref: dev-feature
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          path: mern-app

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies for frontend
        run: |
          cd mern-app/frontend
          npm install

      - name: Build Frontend
        run: |
          cd mern-app/frontend
          npm run build

      - name: Deploy to GitHub Pages
        run: |
          cd mern-app/frontend
          npm install -g serve
          serve -s build -i 3000
